# SPDX-FileCopyrightText: 2021 The unpaper authors
#
# SPDX-License-Identifier: MIT

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - or:
        - "#approved-reviews-by>=1"
        - "author=Flameeyes"
      - "status-success=Build And Test Results"
      - "status-success=pre-commit"
    actions:
      merge:
        method: rebase
