# SPDX-FileCopyrightText: 2021 The unpaper authors
#
# SPDX-License-Identifier: MIT

pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - or:
        - "#approved-reviews-by>=1"
        - "author=Flameeyes"
      - "status-success=Build and test on Linux (gcc, -Dwerror=true)"
      - "status-success=Build and test on Linux (gcc, --buildtype=debugoptimized -Dwerror=true)"
      - "status-success=Build and test on Linux (gcc, --buildtype=debugoptimized -Dwerror=true -Db_lto=true)"
      - "status-success=Build and test on Linux (clang, -Dwerror=true)"
      - "status-success=Build and test on Linux (clang, --buildtype=debugoptimized)"
      - "status-success=Build and test on Linux (clang, --buildtype=debugoptimized -Dwerror=true -Db_lto=true)"
      - "status-success=pre-commit"
    actions:
      merge:
        method: rebase
