# SPDX-FileCopyrightText: 2020 The unpaper authors
#
# SPDX-License-Identifier: MIT

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
-   repo: https://github.com/fsfe/reuse-tool
    rev: v3.0.1
    hooks:
    - id: reuse
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
    -   id: clang-format
