# SPDX-FileCopyrightText: 2005 The unpaper authors
#
# SPDX-License-Identifier: MIT

dist: bionic

language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - libavcodec-dev
      - libavutil-dev
      - libavformat-dev
      - xsltproc
      # The following are for meson:
      - python3
      - python3-pip
      - python3-setuptools
      - python3-wheel
      - ninja-build

install:
  - pip3 install meson

script:
  - export DESTDIR=$(mktemp -d)
  - meson setup builddir
  - meson compile -C builddir
  - meson install -C builddir
